In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 

In [4]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df = df.dropna()

In [6]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
from sklearn import preprocessing

LabelEncoder = preprocessing.LabelEncoder()
df['Gender'] = LabelEncoder.fit_transform(df['Gender'])

df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [8]:
x = df[['Age','EstimatedSalary']]
y = df['Purchased']

print(x.head())
print(y.head())

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000
0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64


In [9]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [13]:
model.score(x_train,y_train)

0.621875

In [14]:
prediction = model.predict(x_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,prediction)

array([[58,  0],
       [22,  0]], dtype=int64)

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_test,prediction,zero_division=0))

              precision    recall  f1-score   support

           0       0.72      1.00      0.84        58
           1       0.00      0.00      0.00        22

    accuracy                           0.73        80
   macro avg       0.36      0.50      0.42        80
weighted avg       0.53      0.72      0.61        80



In [22]:
from sklearn.metrics import accuracy_score,precision_score, precision_recall_fscore_support

precision_recall_fscore_support(y_test,prediction,zero_division=0)

(array([0.725, 0.   ]),
 array([1., 0.]),
 array([0.84057971, 0.        ]),
 array([58, 22], dtype=int64))

In [23]:
df = pd.read_csv('Iris.csv')
df.head()


   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [26]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [27]:
import pandas as pd 
import numpy as np 

import nltk


In [28]:
#nltk.download('all')

In [29]:
from nltk.tokenize import word_tokenize

this_str = 'this is a string and will be divide'

print(word_tokenize(this_str))

['this', 'is', 'a', 'string', 'and', 'will', 'be', 'divide']


In [30]:
from nltk.tokenize import sent_tokenize

text = 'this is one. this is two.'

print(sent_tokenize(text))

['this is one.', 'this is two.']


In [34]:
from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()

words = ['clean','cleaning','cleans','cleaned']

for w in words:
    print(porter_stemmer.stem(w))

clean
clean
clean
clean


In [39]:
from nltk.stem import WordNetLemmatizer

WNL = WordNetLemmatizer()

words = ['clean','cleaning','cleans','cleaned']
for w in words:
    print(WNL.lemmatize(w,pos='v'))

clean
clean
clean
clean


In [40]:
from nltk.corpus import stopwords

print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [45]:
text = 'AI was introduced in the year 1956 but it gained popularity recently.'

stopw = stopwords.words('english')

text = word_tokenize(text)


filtered = []

for ch in text:
    if ch not in stopw:
        filtered.append(ch)
filtered

['AI', 'introduced', 'year', '1956', 'gained', 'popularity', 'recently', '.']

In [47]:
for word in text:
    print(nltk.pos_tag([word]))

[('AI', 'NN')]
[('was', 'VBD')]
[('introduced', 'VBN')]
[('in', 'IN')]
[('the', 'DT')]
[('year', 'NN')]
[('1956', 'CD')]
[('but', 'CC')]
[('it', 'PRP')]
[('gained', 'VBN')]
[('popularity', 'NN')]
[('recently', 'RB')]
[('.', '.')]


In [51]:
import math
from collections import Counter

# Sample documents
documents = [
    "I love coding",
    "Python is my favorite programming language",
    "Coding is fun and rewarding",
    "I enjoy exploring new technologies"
]

# Step 1: Compute term frequency (TF) for each document
tf_documents = []
for doc in documents:
    word_counts = Counter(doc.split())
    total_words = len(doc.split())
    tf_doc = {word: word_counts[word] / total_words for word in word_counts}
    tf_documents.append(tf_doc)

# Step 2: Compute document frequency (DF) for each term
df = Counter()
for doc in documents:
    terms = set(doc.split())
    df.update(terms)

# Step 3: Compute inverse document frequency (IDF) for each term
N = len(documents)
idf = {term: math.log(N / (df[term] + 1)) for term in df}

# Step 4: Compute TF-IDF for each term in each document
tfidf_documents = []
for tf_doc in tf_documents:
    tfidf_doc = {term: tf_doc[term] * idf[term] for term in tf_doc}
    tfidf_documents.append(tfidf_doc)

# Print the TF-IDF weights for each document
for i, tfidf_doc in enumerate(tfidf_documents):
    print(f"Document {i+1}:")
    for term, weight in tfidf_doc.items():
        print(f"{term}: {weight}")
    print()


Document 1:
I: 0.09589402415059362
love: 0.23104906018664842
coding: 0.23104906018664842

Document 2:
Python: 0.11552453009332421
is: 0.04794701207529681
my: 0.11552453009332421
favorite: 0.11552453009332421
programming: 0.11552453009332421
language: 0.11552453009332421

Document 3:
Coding: 0.13862943611198905
is: 0.05753641449035617
fun: 0.13862943611198905
and: 0.13862943611198905
rewarding: 0.13862943611198905

Document 4:
I: 0.05753641449035617
enjoy: 0.13862943611198905
exploring: 0.13862943611198905
new: 0.13862943611198905
technologies: 0.13862943611198905



In [ ]:
import